config/routes.rb
MvVcs::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  scope :module => "request" do
    get "/request/fbvouch/callback" => "fb_vouch#callback"
    resources :fb_vouch, path: "/request/fbvouch"
  end
  
  resources :templates
  resources :accounts
  
  resources :requests do
    resources :responses
    post "/responses/update.ajax" => "responses#update_ajax"
  end
  
  get "/request" => "request#index"
  get "/request/myrequests" => "request#myrequests"
  get "/request/othersrequests" => "request#othersrequests"
  get "/request/:id" => "request#show"

  get "/facebook" => "facebook#index"
  get '/console'  => 'home#console'
  

  root :to => 'home#index'

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Game</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.game %></td>
    <td><%= template.score %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @template.game %>
</p>

<p>
  <b>Score:</b>
  <%= @template.score %>
</p>


<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>